deret = (input("Masukan deret angka anda (Pisahkan dengan koma)\n>> ")).split(",")
pnjg = len(deret)
a = deret.sort(key = lambda deret : int(deret))
maksimum = (deret[pnjg-1]).strip()
minimum = deret[0].strip()
print (f"Angka terbesar dalam inputan >> {maksimum}\nAngka terkecil dalam inputan >> {minimum}")